name: madmom
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - cython>=0.25
  - numpy
  - scipy
  - opencv
  - portaudio
  - pyfftw
  - ffmpeg
  - pip
  - pip:
      - mido>=1.2.6
      - pyaudio
      - flake8<4
      - coverage
      - pytest
      - pytest-cov
      - pytest-flake8
      - black
      - pre-commit
      - prospector
